force-app/main/default/objects/Holding__c/Holding__c.object-meta.xml
<CustomObject>
    <label>Holding</label>
    <nameField>
        <label>Holding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holdings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Holding__c.field-meta.xml
<CustomField>
    <fullName>Holding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holding</label>
    <referenceTo>Holding__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Order__c/Stock_Order__c.object-meta.xml
<CustomObject>
    <label>Stock Order</label>
    <nameField>
        <label>Stock Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Order__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Stock Orders</relationshipLabel>
    <relationshipName>Stock_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockRetriver.cls
public  class StockRetriver {
    // public static QuerySelector selectedQueries = new QuerySelector();
    // @AuraEnabled
    // public static List<Holding__c> retriveStockHoldings(){
    //     try {
            
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }
    // public List<Holding__c> reverseDataToParentChild(List<Stock_Order__c> stockOrders){
    //     Map<Id,Holding__c> holdingMap = new Map<Id,Holding__c>();
    //     for(Stock_Order__c stockOrder:stockOrders){
    //         if(holdingMap.containsKey(Stock__r.Holding__c)){
    //             holdingMap.get(Stock__r.Holding__c);
    //         }
    //         else{
    //             Holding__c holding= new Holding__c
    //         }
    //     }

    // }
    // public class QuerySelector{
    //     public List<Stock_Order__c> stockOrderRetrive(Id holdingId){
    //         return [SELECT Id,Name,Stock__c,Stock__r.Name,Stock__r.Holding__r.Name,Stock__r.Holding__c FROM Stock_Order__c WHERE Stock__r.Holding__c=:holdingId ];
    //     }
    // }
}